### ISSUE TITLE
Anonymous Reactions

### ISSUE THREAD

**Issue by rishiosaur** [ifvictr/prox#27]
If replies are anonymous, then shouldn't reactions be as well? They're a super quick way to get a point across and express your feelings, and I think that it'd be a really cool thing to add in. @ifvictr can I try my hand at doing this, if you agree?

**Comment by ifvictr** [comment]
Would this only work for OP? Or are you trying to make it open to everyone else? As far as I know, Slack only allows each user to react to a message with a particular emoji once.

**Comment by rishiosaur** [comment]
Yeah, I think it'd be only for the OP.

**Comment by ifvictr** [comment]
@rishiosaur Great! Feel free to take a stab at it.
